### ISSUE TITLE
Craft 5 support

### ISSUE THREAD

**Issue by ishetnogferre** [jalendport/craft-preparse#98]
Hi, 

We're in the process of updating our boilerplate and was wondering if support for Craft 5 is planned?

Thanks!

**Comment by steve-moresoda** [comment]
Any updates on this?

**Comment by jalendport** [comment]
Thanks all for your patience; Craft 5 version is coming very soon! Waiting for P&T to finalize the transfer in the plugin store (you might have already noticed the repo change), and then I'll have a new version out for you all shortly after that...

**Comment by tomkiss** [comment]
Just to say- thanks for all your work on this Jalen!

Really great to see this plugin get some love 💯

**Comment by jalendport** [comment]
@tomkiss sure thing!

**Comment by jalendport** [comment]
📢 Craft 5 support is out now as `3.0.0-alpha.1` 🎉 I tagged it as an alpha because I plan on rewriting the plugin from the ground up so that I can hopefully clear out some of the bugs and issues that have accumulated over the years, and also start taking advantage of some of the new features. (There will be a migration path when v3 is fully released fyi...) In the meantime you can use the alpha (which should be stable enough) to get your sites upgraded to Craft 5.
